# Generated by Django 3.2.2 on 2021-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0024_auto_20210605_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
