# Generated by Django 3.2.2 on 2021-06-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0026_alter_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
